#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5
bspc config pointer_motion_interval 7ms

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme alternate
bspc config initial_polarity second_child


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a pwvucontrol state=floating rectangle=800x600+1120+240

pgrep -x picom > /dev/null && killall picom
picom --config ~/.config/picom/picom.conf -b
nitrogen --restore &
xset s off
xset -dpms


$HOME/polybar-collection/launch.sh
