#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

" - Display - "
bspc monitor -d 1 2 3 4 5
bspc config pointer_motion_interval 7ms
" -----------------"


" - Configs - " 
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
" -----------------"


" - Rules - "
bspc rule -a pwvucontrol state=floating rectangle=800x600+1120+240
bspc rule -a spectacle state=floating rectangle=800x600+1120+240
bspc rule -a kcalc state=floating rectangle=400x650+1120+240
bspc rule -a discord desktop='^2'
" -----------------"


" - Misc - "
pgrep -x picom > /dev/null && killall picom
picom --config ~/.config/picom/picom.conf -b
nitrogen --restore &
xset s off
xset -dpms
(sleep 2 && setxkbmap -layout us,br -option grp:ctrl_space_toggle) &
" -----------------"


$HOME/polybar-collection/launch.sh
